name: english_secrets
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.14.2
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.16
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # The Flutter code generator for your assets, fonts, colors.
  flutter_gen_runner: ^5.8.0

  animated_text_kit: ^4.2.2
  # Use dynamic and beautiful card view pagers to help you create great apps.
  vertical_card_pager: ^1.6.2
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.0+3
  icon_broken: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
