name: english_secrets
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.14.2
  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.16
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.14
  # The Flutter code generator for your assets, fonts, colors.
  flutter_gen_runner: ^5.8.0

  animated_text_kit: ^4.2.2
  # Use dynamic and beautiful card view pagers to help you create great apps.
  vertical_card_pager: ^1.6.2
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.0+3
  # Sleek, crystal-clear blur bottom navigation bar with dynamic indicator for seamless app navigation.
  crystal_navigation_bar: ^1.0.2
  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.6
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.7
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.4
  # Loading animation or loading spiner or loader. It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.3.0
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^8.0.3
  # A progress bar widget to show or change the position of an audio or video stream.
  audio_video_progress_bar: ^2.0.3
  # A Flutter package project that is a simple animation listview widget.
  animation_list: ^3.1.0
  # Blast colorful confetti all over the screen. Celebrate in app achievements with style. Control the velocity, angle, gravity and amount of confetti.
  confetti: ^0.8.0
  icon_broken: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
